// Electron Forge configuration.
// Docs: https://www.electronforge.io/configuration
const path = require('path');
const pkg = require('./package.json');

module.exports = {
  packagerConfig: {
    // Name shown on the executable, shortcuts and installer.
    name: pkg.productName || pkg.name,
    // Safe file name for the .exe (no spaces) so Squirrel and shortcuts
    // behave predictably on Windows.
    executableName: 'WolfPet',
    // Bundle app code into an asar archive (industry default — faster
    // startup, harder to poke around in, avoids long-path issues).
    asar: true,
    // App icon. electron-packager appends the right extension per platform
    // (.ico on Windows). build/icon.ico is generated by
    // scripts/generate-icon.js during the installer build; when it's absent
    // packager falls back to the default Electron icon with a warning.
    icon: path.join(__dirname, 'build', 'icon'),
  },
  // Where packaged output + maker artifacts go. NOTE: this is the top-level
  // `outDir` option — Forge ignores `packagerConfig.out` and resolves its own
  // out dir via the top-level property (see @electron-forge/core out-dir.ts).
  // scripts/make-installer.js points this at a temp dir (FORGE_OUT) so heavy
  // builds don't churn an actively syncing OneDrive/AV folder; plain
  // `npm run make` uses ./out as usual.
  outDir: process.env.FORGE_OUT || 'out',
  rebuildConfig: {},
  makers: [
    // Windows installer (NSIS-free, Squirrel.Windows based) — produces
    // out/make/squirrel.windows/x64/WolfPet-<version> Setup.exe
    {
      name: '@electron-forge/maker-squirrel',
      config: {
        name: 'WolfPet',
        authors: pkg.author || 'Wolf Pet',
        description: pkg.description,
        setupIcon: path.join(__dirname, 'build', 'icon.ico'),
        // No MSI; a single portable Setup.exe is what most users want.
        noMsi: true,
      },
    },
    // Portable zip of the unpackaged app — handy for "no install" use and
    // for any store/portable distribution later.
    {
      name: '@electron-forge/maker-zip',
      platforms: ['win32'],
    },
  ],
};
