// Electron Forge configuration.
// Docs: https://www.electronforge.io/configuration
const path = require('path');
const pkg = require('./package.json');

module.exports = {
  packagerConfig: {
    // Name shown on the executable, shortcuts and installer.
    name: pkg.productName || pkg.name,
    // Safe file name for the .exe (no spaces) so Squirrel and shortcuts
    // behave predictably on Windows.
    executableName: 'Halo',
    // Bundle app code into an asar archive (industry default — faster
    // startup, harder to poke around in, avoids long-path issues).
    asar: true,
    // Only ship what the app needs at runtime. Every window loads its HTML
    // over file:// and main.js/preload.js require nothing but Node built-ins,
    // so node_modules (a ~350 MB devDependency wall incl. the electron pkg)
    // plus build tooling, tests, landing-page assets and old build outputs are
    // pure dead weight in the installer. Without this list a 467 MB asar was
    // being shipped (electron-forge does not prune devDependencies), which is
    // what made the Setup.exe weigh ~160 MB. With it the asar drops to a few
    // MB and the installer loses roughly half its size.
    //
    // Patterns match against the rooted path with either slash direction, so
    // they work identically on Windows and macOS.
    ignore: [
      /[\\/]node_modules[\\/]/,   // no runtime deps — main.js uses only built-ins
      /[\\/]out[\\/]/,           // stale packaged builds from local runs
      /[\\/]dist[\\/]/,          // local release artifacts (never bundle the installer in itself)
      /[\\/]build[\\/]/,         // icons are read from disk by the packager, not the asar
      /[\\/]scripts[\\/]/,       // build scripts
      /[\\/]test[\\/]/,          // unit tests
      /[\\/]\.github[\\/]/,     // CI workflows
      /[\\/]\.freebuff[\\/]/,   // assistant runtime data
      /(?:^|[\\/])\.git(?:[\\/]|$)/,
      /(?:^|[\\/])\.gitignore$/,
      /(?:^|[\\/])\.vercelignore$/,
      /(?:^|[\\/])package-lock\.json$/,
      /(?:^|[\\/])index\.html$/,             // landing page (web only — the app uses app.html)
      /(?:^|[\\/])landing-preview-[^\\/]+\.png$/,
      /(?:^|[\\/])server\.js$/,              // browser-preview only
    ],
    // App icon. electron-packager appends the right extension per platform
    // (.ico on Windows). build/icon.ico is generated by
    // scripts/generate-icon.js during the installer build; when it's absent
    // packager falls back to the default Electron icon with a warning.
    icon: path.join(__dirname, 'build', 'icon'),
  },
  // Where packaged output + maker artifacts go. NOTE: this is the top-level
  // `outDir` option — Forge ignores `packagerConfig.out` and resolves its own
  // out dir via the top-level property (see @electron-forge/core out-dir.ts).
  // scripts/make-installer.js points this at a temp dir (FORGE_OUT) so heavy
  // builds don't churn an actively syncing OneDrive/AV folder; plain
  // `npm run make` uses ./out as usual.
  outDir: process.env.FORGE_OUT || 'out',
  rebuildConfig: {},
  makers: [
    // Windows installer (NSIS-free, Squirrel.Windows based) — produces
    // out/make/squirrel.windows/x64/Halo-<version> Setup.exe
    {
      name: '@electron-forge/maker-squirrel',
      platforms: ['win32'],
      config: {
        name: 'Halo',
        authors: pkg.author || 'Halo',
        description: pkg.description,
        setupIcon: path.join(__dirname, 'build', 'icon.ico'),
        // No MSI; a single portable Setup.exe is what most users want.
        noMsi: true,
      },
    },
    // macOS installer (.dmg). Can only be built ON macOS (appdmg/hdiutil),
    // so the macOS build runs in GitHub Actions — see
    // .github/workflows/release.yml.
    {
      name: '@electron-forge/maker-dmg',
      platforms: ['darwin'],
      config: {
        // Volume/app name inside the DMG. The file itself is renamed to
        // Halo.dmg by the release workflow to match the landing page.
        name: 'Halo',
      },
    },
    // Portable zip of the unpackaged app — handy for "no install" use and
    // for any store/portable distribution later.
    {
      name: '@electron-forge/maker-zip',
      platforms: ['win32', 'darwin'],
    },
  ],
};
